using BaseLib.Extensions;
using Godot;
using MegaCrit.Sts2.Core.Assets;
using MegaCrit.Sts2.Core.Nodes.Combat;

namespace BaseLib.Utils;

public static class GodotUtils
{
    /// <summary>
    /// Creatures an NCreatureVisuals from an image.
    /// </summary>
    /// <param name="path">Filepath to an image that can be loaded as a Texture2D.</param>
    /// <returns></returns>
    public static NCreatureVisuals CreatureVisualsFromImage(string path)
    {
        if (!ResourceLoader.Exists(path))
            throw new Exception("$Attempted to create NCreatureVisuals from path that doesn't exist {path}");
            
        var img = PreloadManager.Cache.GetTexture2D(path);
        var imgSize = img.GetSize();
        var boundsSize = img.GetSize() * 1.1f;
            
        var visualsNode = new NCreatureVisuals();
            
        var bounds = new Control();
        visualsNode.AddUnique(bounds, "Bounds");
        bounds.Position = new(-boundsSize.X / 2, -boundsSize.Y);
        bounds.Size = boundsSize;

        var visuals = new Sprite2D();
        visualsNode.AddUnique(visuals, "Visuals");
        visuals.Texture = img;
        visuals.Position = new(0, -imgSize.Y * 0.5f); //Sprite2D position is centered
            
        var intent = new Marker2D();
        visualsNode.AddUnique(intent, "IntentPos");
        intent.Position = bounds.Position + (bounds.Size * new Vector2(0.5f, 0f)) + new Vector2(0, -70);
            
        var center = new Marker2D();
        visualsNode.AddUnique(center, "CenterPos");
        center.Position = bounds.Position + (bounds.Size * new Vector2(0.5f, 0.6f));
            
        return visualsNode;
    }
    
    public static NCreatureVisuals CreatureVisualsFromScene(string path)
    {
        Node n = PreloadManager.Cache.GetScene(path).Instantiate();
        if (n is NCreatureVisuals visuals)
        {
            MainFile.Logger.Info("Visuals are NCreatureVisuals, returning directly");
            return visuals;
        }
        MainFile.Logger.Info("Visuals are not NCreatureVisuals, attempting conversion");
        
        var visualsNode = new NCreatureVisuals();
        var missing = TransferNodes(visualsNode, n, "Visuals", "Bounds", "IntentPos", "CenterPos", "OrbPos", "TalkPos");

        var bounds = visualsNode.GetNodeOrNull<Control>("%Bounds");
        if (bounds == null) throw new Exception("Creature scene must include a valid Bounds control node.");
        
        //Generate anything not included
        foreach (var key in missing)
        {
            switch (key)
            {
                case "Visuals":
                case "Bounds":
                    throw new Exception("Creature scene must include at least Visuals and Bounds nodes.");
                case "IntentPos":
                    var intent = new Marker2D();
                    visualsNode.AddUnique(intent, "IntentPos");
                    intent.Position = bounds.Position + (bounds.Size * new Vector2(0.5f, 0f)) + new Vector2(0, -70);
                    break;
                case "CenterPos":
                    var center = new Marker2D();
                    visualsNode.AddUnique(center, "CenterPos");
                    center.Position = bounds.Position + (bounds.Size * new Vector2(0.5f, 0.6f));
                    break;
                //OrbPos and TalkPos are optional and will be autogenerated if not provided.
            }
        }
        
        return visualsNode;
    }

    public static T TransferAllNodes<T>(this T obj, string sourceScene, params string[] uniqueNames) where T : Node
    {
        var target = PreloadManager.Cache.GetScene(sourceScene).Instantiate();
        var missing = TransferNodes(obj, target, uniqueNames);
        if (missing.Count > 0)
        {
            MainFile.Logger.Warn($"Created {target.GetType().FullName} missing required children {string.Join(" ", missing)}");
        }
        return obj;
    }
    

    private static List<string> TransferNodes(Node target, Node source, params string[] names)
    {
        return TransferNodes(target, source, true, names);
    }
    private static List<string> TransferNodes(Node target, Node source, bool uniqueNames, params string[] names)
    {
        target.Name = source.Name;

        /*if (target is Control targetControl && source is Control sourceControl)
        {
            transfer node properties?
        }*/

        List<string> requiredNames = [.. names];
        foreach (var child in source.GetChildren())
        {
            source.RemoveChild(child);
            if (requiredNames.Remove(child.Name) && uniqueNames) child.UniqueNameInOwner = true;
            target.AddChild(child);
            child.Owner = target;

            SetChildrenOwner(target, child);
        }

        /*if (requiredNames.Count > 0)
        {
            MainFile.Logger.Warn($"Created {target.GetType().FullName} missing required children {string.Join(" ", requiredNames)}");
        }*/

        source.QueueFree();
        return requiredNames;
    }

    private static void SetChildrenOwner(Node target, Node child)
    {
        foreach (var grandchild in child.GetChildren())
        {
            grandchild.Owner = target;
            SetChildrenOwner(target, grandchild);
        }
    }
}
